ROOT=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
LIB_PATH=$ROOT/lib
INCLUDE_PATH=$ROOT/include

export LD_LIBRARY_PATH=$LIB_PATH:$LD_LIBRARY_PATH
export LIBRARY_PATH=$LIB_PATH:$LIBRARY_PATH
export CPATH=$INCLUDE_PATH:$CPATH
